version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped

    ports:
      - "5001:5001"

    env_file:
      - ./server/.env

    environment:
      NODE_ENV: production

    networks:
      - todoflow-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: http://localhost:5001/api

    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - server

    networks:
      - todoflow-network

networks:
  todoflow-network:
    driver: bridge
